name: CI/CD Pipeline with Docker and Trivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and tag the Docker image using the commit SHA
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dockerCICD:${{ github.sha }} .

      # Push the Docker image to DockerHub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dockerCICD:${{ github.sha }}

  trivy-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      # Pull the Docker image for scanning
      - name: Pull Docker Image for Scanning
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/dockerCICD:${{ github.sha }}

      # Scan the image for vulnerabilities using Trivy
      - name: Run Trivy Vulnerability Scan
        run: ./bin/trivy image ${{ secrets.DOCKER_USERNAME }}/dockerCICD:${{ github.sha }}

